notes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('notices.urls')),
]

notices/urls.py
"""Defines URL patterns for notices"""

from django.urls import path
from . import views

app_name = 'notices'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),

    # All notes
    path('notes/', views.notes, name='notes'),


    # Detail page for a single note
    path('notes/<int:note_id>/', views.note, name="note"),

    # Page for adding new notes
    path('new_note/', views.new_note, name="new_note"),

    # Page for adding new content
    path('new_content/<int:note_id>/', views.new_content, name="new_content"),
    #path('new_content/<int:note_id>/', views.delete_content, name="delete_content"),

    # Page for editing content
    path('edit_content/<int:content_id>/', views.edit_content, name='edit_content'),

    path('delete_note/<int:note_id>/', views.delete_note, name='delete_note'),
]

users/urls.py
"""URL patterns for users"""

from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'users'
urlpatterns = [
    # Login page
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'),

    # Logout page
    path('logout/', LogoutView.as_view(), name='logout'),

    # Registration page
    path('register/', views.register, name='register'),
]

notices/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Note(models.Model):
    """ Note title. """
    text = models.CharField(max_length=600)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """return string model"""
        return self.text


class Content(models.Model):
    """Content of note."""
    note = models.ForeignKey(Note, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    # class Meta

    def __str__(self):
        if self.text[50:]:
            return self.text[:50] + "..."
        else:
            return self.text[:50]

users/models.py
from django.db import models

# Create your models here.

notices/forms.py
from django import forms
from .models import Note, Content


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['text']
        labels = {'text': ''}


class ContentForm(forms.ModelForm):
    class Meta:
        model = Content
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

notices/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .models import Note, Content
from .forms import NoteForm, ContentForm
from django.contrib.auth.decorators import login_required

# Create your views here.


def index(request):
    """Home page of app"""
    return render(request, 'notices/index.html')


@login_required
def notes(request):
    """All notes"""
    notes = Note.objects.filter(owner=request.user).order_by('date_added')
    context = {'notes': notes}
    return render(request, 'notices/notes.html', context)


@login_required
def note(request, note_id):
    """Show single note and its content"""
    note = Note.objects.get(id=note_id)
    #current user-topic checkout
    if note.owner != request.user:
        raise Http404
    self_content = note.content_set.order_by('-date_added')
    context = {'note': note, 'content': self_content}
    return render(request, 'notices/note.html', context)


@login_required
def new_note(request):
    """Define a new note"""
    if request.method != 'POST':
        # No data, create empty form
        form = NoteForm()
    else:
        # data POST sent, process the data
        form = NoteForm(request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.owner = request.user
            new_note.save()
            return HttpResponseRedirect(reverse('notices:notes'))

    context = {'form': form}
    return render(request, 'notices/new_note.html', context)


@login_required
def new_content(request, note_id):
    """Adding new content for particular note"""
    note = Note.objects.get(id=note_id)

    if request.method != 'POST':
        # No data, create empty form
        form = ContentForm()
    else:
        # data POST sent, process the data
        form = ContentForm(data=request.POST)
        if form.is_valid():
            new_content = form.save(commit=False)
            new_content.note = note
            new_content.save()
            return HttpResponseRedirect(reverse('notices:note',
                                                args=[note_id]))

    context = {'note': note, 'form': form}
    return render(request, 'notices/new_content.html', context)


@login_required
def edit_content(request, content_id):
    """Editing note"""
    content = Content.objects.get(id=content_id)
    note = content.note

    if note.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = ContentForm(instance=content)
    else:
        form = ContentForm(instance=content, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('notices:note',
                                                args=[note.id]))

    context = {'content': content, 'note': note, 'form': form}
    return render(request, 'notices/edit_content.html', context)


@login_required
def delete_note(request, note_id):
    note = Note.objects.get(id=note_id)
    form = NoteForm(request.POST)
    notes = Note.objects.filter(owner=request.user).order_by('date_added')

    note.delete()
    #context = {'form': form}
    context = {'notes': notes}
    return render(request, 'notices/notes.html', context)


@login_required
def delete_content(request, noted_id):
    pass

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate

# Create your views here.


def register(request):
    """Registrate new user"""
    if request.method != 'POST':
        # Display blank registration form
        form = UserCreationForm()

    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу.
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('notices:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

notices/templates/notices/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Notes</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-dark bg-dark" style="background-color: #e3f2fd;">
      <div class="container-fluid">

        <div class="navbar-header"> <!-- кнопка "Notices app"-->
          <button type="button" class="navbar-toggle collapsed"
                  data-toggle="collapse" data-taget="#navbar"
                  aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'notices:index' %}">
            Notices app</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav"> <!-- кнопка Notes -->
            <li><a href="{% url 'notices:notes' %}">Notes</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">log out</a></li> <!-- кнопка выхода -->
            {% else %}
              <li><a href="{% url 'users:register' %}">register</a></li> <!-- кнопка рег. -->
              <li><a href="{% url 'users:login' %}">log in</a></li> <!-- кнопка входа -->
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->

      </div>

    </nav>

    <!-- <nav class="navbar bg-light">
      <div class="container">
        <a class="navbar-brand" href="#">
          <img src="/docs/5.2/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24">
        </a>
      </div>
    </nav> -->


    <div class="container">
      <div class="page-header">
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>

    </div> <!-- /container -->

  </body>
</html>

notices/templates/notices/delete_note.html
{% extends 'notices/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <!--<h2>del <a href="{% url 'notices:note' note.id %}">{{ note }}</a></h2> -->
{% endblock header %}

{% block content %}

  <form action="{% url 'notices:delete_note' note.id %}" method="post"
        class="form">
      {% csrf_token %}
      {% bootstrap_form form %}

      {% buttons %}
        <button name="submit">delete</button>
      {% endbuttons %}
  </form>

{% endblock content %}

notices/templates/notices/edit_content.html
{% extends "notices/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Edit content:</h2>
  <h2><a href="{% url 'notices:note' note.id %}">{{ note }}</a></h2>
{% endblock header %}

{% block content %}

  <form action="{% url 'notices:edit_content' content.id %}" method="post"
        class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit">save changes</button>
    {% endbuttons %}

  </form>

{% endblock content %}

notices/templates/notices/index.html
{% extends "notices/base.html" %}

{% block header %}
  <div class="jumpotron">
    <h1>Track your notes.</h1>
  </div>
{% endblock header %}

{% block content %}
  {% if not user.is_authenticated %}
    <h2>
      <a href="{% url 'users:register' %}">Register an account</a> to make
        your own notes.
    </h2> <!-- block if base.html? -->
  {% endif %}
  <h2>
    You can write everything you want in the "Notes".
    Be free in your mindstorm process.
  </h2>
{% endblock content %}

notices/templates/notices/new_content.html
{% extends 'notices/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new content for
    <a href="{% url 'notices:note' note.id %}">{{ note }}</a>
  </h2>
  <!-- <h2><a href="{% url 'notices:note' note.id %}">{{ note }}</a></h2> -->
{% endblock header %}

{% block content %}

  <form action="{% url 'notices:new_content' note.id %}" method="post"
        class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit">add content</button>
    {% endbuttons %}
  </form>

{% endblock content %}

notices/templates/notices/new_note.html
{% extends 'notices/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>Add a new note:</h2>
{% endblock header %}

{% block content %}

  <form action="{% url 'notices:new_note' %}" method="post"
        class="form">

    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">add note</button>
    {% endbuttons %}

  </form>

{% endblock content %}

notices/templates/notices/note.html
{% extends 'notices/base.html' %}

{% block header %}
  <h2>{{ note }}</h2>
{% endblock header %}

{% block content %}

  <p>
    <a href="{% url 'notices:new_content' note.id %}">add new content</a>
  </p>

  {% for content in content %}
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3>
          {{ content.date_added|date:'M d, Y H:i' }}
          <small>
            <a href="{% url 'notices:edit_content' content.id %}">
              edit content</a>
          </small>
        </h3>
      </div>
      <div class="panel-body">
        {{ content.text|linebreaks }}
      </div>
    </div> <!-- panel -->

    {% empty %}
      There are no info for this Note yet.
    {% endfor %}

{% endblock content%}

notices/templates/notices/notes.html
{% extends "notices/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h1>Notes</h1>
{% endblock header %}

{% block content %}

  <ul>
    {% for note in notes %}
      <li>
        <h3>
          <a href="{% url 'notices:note' note.id %}">{{ note }}</a>
          <a href="{% url 'notices:delete_note' note.id %}" class="text-danger">Delete</a>
        </h3>
      </li>
    {% empty %}
      <li>No notes have been added yet.</li>
    {% endfor %}
  </ul>

    <h3>
      <a href="{% url 'notices:new_note' %}" class="text-success">Add a new note</a>
    </h3>

{% endblock content %}

users/templates/users/login.html
{% extends 'notices/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}


    <input type="hidden" name="next"
           value="{% url 'notices:index' %}" />
  </form>

{% endblock content %}

users/templates/users/register.html
{% extends "notices/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h1>You can registrate an account.</h1>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}"
        class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit">register</button>
    {% endbuttons %}

    <input type="hidden" name="next"
           value="{% url 'notices:index' %}" />
  </form>

{% endblock content %}